---
title: "Replication of the study on: How Quick Decisions Illuminate Moral Character  (2012, Social Psychological and Personality Science)"
author: "Clayton R. Critcher, Yoel Inbar and David A. Pizarro"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

My research interests currently lie at the intersection of machine learning, neural networks, social networks, human rights, and political science as I am in the Computational Social Science M.S. program, currently working on a project with the political science department. However, I feel excited to have been given an opportunity to explore my interests in the field of social psychology and find ways in which these may overlap with my other interests. More specifically, I have chosen this experiment on moral character because I have always had a fascination with morality and ethics as it relates to human behavior, social networks, and more broadly, human rights. This study piqued my interest because of its evaluation of both moral character, but also how others perceive other individuals based on not only their actions or non-actions but the way in which they come to these decisions. Studies such as this may provide insight into social dynamics and perceptions which may prove helpful in understanding broader social phenomena. 


This experiment will require a relatively large sample size of around 100-120. The original involves both students and other members of the community, which would probably be the case in its replication. Aside from the sample, the actual experiment itself does not pose great challenges in that it simply involves coming up with a scenario in which there are four cases: one in which an individual comes to a “moral” decision quickly, one where the same individual comes to the same decision after a longer time of consideration, another where another individual comes to an “immoral” decision quickly, and lastly, one where the same individual comes to the same “immoral” decision after some consideration. Following the disclosure of these four scenarios, the participants will be surveyed on their opinions regarding the following: quickness, moral character, certainty, emotional impulsivity. I believe that the challenges of replicating this study will mainly be in finding a random sample of participants and distributing the surveys. Because the risks and bias factors are relatively low in this specific study/experiment, there are not as many challenges in its replication. The analysis itself once the results have been gathered will be straightforward. 

[Project Repository](https://github.com/sahamidi2/critcher2012)
<br>
[Original Paper](https://github.com/sahamidi2/critcher2012/blob/main/original_paper/critcher-et-al-2012-how-quick-decisions-illuminate-moral-character.pdf)

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
